<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406174800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('DROP INDEX type_absence_id ON absence');
        $this->addSql('DROP INDEX fk_absence_user ON absence');
        $this->addSql('ALTER TABLE absence CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE heure_debut heure_debut VARCHAR(5) NOT NULL, CHANGE heure_fin heure_fin VARCHAR(5) NOT NULL, CHANGE duree_minutes duree_minutes INT NOT NULL, CHANGE motif motif VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE actionpdi DROP FOREIGN KEY `actionpdi_ibfk_1`');
        $this->addSql('ALTER TABLE actionpdi DROP FOREIGN KEY `fk_actionPDI_formation`');
        $this->addSql('ALTER TABLE actionpdi ADD type_action VARCHAR(100) NOT NULL, ADD date_debut DATE NOT NULL, ADD date_fin_prevue DATE NOT NULL, DROP typeAction, DROP dateDebut, DROP dateFinPrevue, CHANGE id id INT NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL, CHANGE priorite priorite INT NOT NULL, CHANGE pdi_id pdi_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE actionpdi ADD CONSTRAINT FK_653CF31897CD944 FOREIGN KEY (pdi_id) REFERENCES pdi (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actionpdi ADD CONSTRAINT FK_653CF3185200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actionpdi RENAME INDEX idx_action_pdi TO IDX_653CF31897CD944');
        $this->addSql('ALTER TABLE actionpdi RENAME INDEX idx_action_formation TO IDX_653CF3185200282E');
        $this->addSql('DROP INDEX fk_candidature_poste ON candidature');
        $this->addSql('ALTER TABLE candidature CHANGE id id INT NOT NULL, CHANGE poste_interne_id poste_interne_id INT NOT NULL, CHANGE candidat_id candidat_id INT NOT NULL, CHANGE employe_id employe_id INT NOT NULL, CHANGE type_candidat type_candidat VARCHAR(50) NOT NULL, CHANGE date_depot date_depot DATE NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE etape_pipeline etape_pipeline VARCHAR(50) NOT NULL, CHANGE scoring_ia scoring_ia DOUBLE PRECISION NOT NULL, CHANGE cv_url cv_url VARCHAR(255) NOT NULL, CHANGE lettre_motivation_url lettre_motivation_url VARCHAR(255) NOT NULL, CHANGE derniere_modification derniere_modification DATE NOT NULL, CHANGE commentaires_rh commentaires_rh LONGTEXT NOT NULL, CHANGE salaire_pretendu salaire_pretendu DOUBLE PRECISION NOT NULL, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE prenom prenom VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(100) NOT NULL');
        $this->addSql('DROP INDEX fk_candidature_poste ON candidature_externe');
        $this->addSql('ALTER TABLE candidature_externe CHANGE id id INT NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE etape_pipeline etape_pipeline VARCHAR(50) NOT NULL, CHANGE scoring_ia scoring_ia DOUBLE PRECISION NOT NULL, CHANGE cv_url cv_url VARCHAR(255) NOT NULL, CHANGE lettre_motivation_url lettre_motivation_url VARCHAR(255) NOT NULL, CHANGE derniere_modification derniere_modification DATETIME NOT NULL');
        $this->addSql('ALTER TABLE candidature_interne CHANGE id id INT NOT NULL, CHANGE nouveau_salaire nouveau_salaire DOUBLE PRECISION NOT NULL, CHANGE motif motif LONGTEXT NOT NULL, CHANGE derniere_modification derniere_modification DATETIME NOT NULL');
        $this->addSql('ALTER TABLE categoriecompetence CHANGE couleur couleur VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE categorieformation CHANGE id id INT NOT NULL, CHANGE couleur couleur VARCHAR(50) NOT NULL');
        $this->addSql('DROP INDEX espace_id ON chaise');
        $this->addSql('ALTER TABLE chaise CHANGE id id INT NOT NULL, CHANGE espace_id espace_id INT NOT NULL, CHANGE chair_number chair_number INT NOT NULL');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE publicationId publicationId INT DEFAULT NULL, CHANGE authorId authorId INT DEFAULT NULL, CHANGE dateCreation dateCreation DATETIME NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE nombreReactions nombreReactions INT NOT NULL');
        $this->addSql('ALTER TABLE commentaire RENAME INDEX idx_comment_pub TO IDX_67F068BC796DA8A');
        $this->addSql('ALTER TABLE commentaire RENAME INDEX idx_comment_author TO IDX_67F068BCA196F9FD');
        $this->addSql('ALTER TABLE competence DROP FOREIGN KEY `competence_ibfk_1`');
        $this->addSql('ALTER TABLE competence CHANGE id id INT NOT NULL, CHANGE typeCompetence typeCompetence VARCHAR(100) NOT NULL, CHANGE statutCompetence statutCompetence VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE competence ADD CONSTRAINT FK_94D4687FBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categoriecompetence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE competence RENAME INDEX categorie_id TO IDX_94D4687FBCF5E72D');
        $this->addSql('DROP INDEX idx_emp_comp ON competence_niveau_history');
        $this->addSql('ALTER TABLE competence_niveau_history CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE competenceemploye DROP FOREIGN KEY `fk_ce_competence`');
        $this->addSql('ALTER TABLE competenceemploye DROP FOREIGN KEY `fk_ce_utilisateur`');
        $this->addSql('DROP INDEX uq_employe_competence ON competenceemploye');
        $this->addSql('ALTER TABLE competenceemploye ADD niveau_valide TINYINT NOT NULL, ADD preuve_url VARCHAR(255) NOT NULL, ADD date_evaluation DATE NOT NULL, DROP niveauValide, DROP preuveUrl, DROP dateEvaluation, CHANGE id id INT NOT NULL, CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE competence_id competence_id INT DEFAULT NULL, CHANGE niveauActuel niveau_actuel INT NOT NULL');
        $this->addSql('ALTER TABLE competenceemploye ADD CONSTRAINT FK_48D451261B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE competenceemploye ADD CONSTRAINT FK_48D4512615761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE competenceemploye RENAME INDEX employe_id TO IDX_48D451261B65292');
        $this->addSql('ALTER TABLE competenceemploye RENAME INDEX competence_id TO IDX_48D4512615761DAB');
        $this->addSql('DROP INDEX type_conge_id ON conge');
        $this->addSql('DROP INDEX fk_conge_user ON conge');
        $this->addSql('ALTER TABLE conge CHANGE statut statut VARCHAR(50) NOT NULL');
        $this->addSql('DROP INDEX uq_espace_chair_date ON coworking_reservations');
        $this->addSql('ALTER TABLE coworking_reservations CHANGE id id INT NOT NULL');
        $this->addSql('DROP INDEX absence_id ON demande_absence');
        $this->addSql('ALTER TABLE demande_absence CHANGE id id INT NOT NULL, CHANGE motif motif LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL');
        $this->addSql('DROP INDEX conge_id ON demande_conge');
        $this->addSql('ALTER TABLE demande_conge CHANGE id id INT NOT NULL, CHANGE motif motif LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE document CHANGE id id INT NOT NULL, CHANGE uploaded_at uploaded_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX matricule ON employe');
        $this->addSql('DROP INDEX manager_id ON employe');
        $this->addSql('ALTER TABLE employe CHANGE matricule matricule VARCHAR(50) NOT NULL, CHANGE poste_actuel poste_actuel VARCHAR(100) NOT NULL, CHANGE date_embauche date_embauche DATE NOT NULL, CHANGE departement departement VARCHAR(100) NOT NULL, CHANGE manager_id manager_id INT NOT NULL');
        $this->addSql('DROP INDEX matricule ON employe_competence');
        $this->addSql('DROP INDEX idx_employe_matricule ON employe_competence');
        $this->addSql('DROP INDEX idx_employe_departement ON employe_competence');
        $this->addSql('ALTER TABLE employe_competence ADD poste_actuel VARCHAR(255) NOT NULL, ADD date_embauche DATE NOT NULL, DROP posteActuel, DROP dateEmbauche, CHANGE id id INT NOT NULL, CHANGE Departement departement VARCHAR(255) NOT NULL, CHANGE nom nom VARCHAR(50) NOT NULL');
        $this->addSql('DROP INDEX fk_entretien_candidature ON entretien_recrutement');
        $this->addSql('ALTER TABLE entretien_recrutement CHANGE id id INT NOT NULL, CHANGE candidature_externe_id candidature_externe_id INT NOT NULL, CHANGE type_entretien type_entretien VARCHAR(50) NOT NULL, CHANGE date_entretien date_entretien DATE NOT NULL, CHANGE heure_debut heure_debut VARCHAR(255) NOT NULL, CHANGE heure_fin heure_fin VARCHAR(255) NOT NULL, CHANGE intervieweurs_ids intervieweurs_ids LONGTEXT NOT NULL, CHANGE salle salle VARCHAR(50) NOT NULL, CHANGE url_visio url_visio VARCHAR(255) NOT NULL, CHANGE statut_entretien statut_entretien VARCHAR(50) NOT NULL, CHANGE note_entretien note_entretien DOUBLE PRECISION NOT NULL, CHANGE duree duree INT NOT NULL');
        $this->addSql('DROP INDEX nom ON equipement');
        $this->addSql('ALTER TABLE equipement CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE espaces ADD liste_equipements LONGTEXT NOT NULL, ADD url_image LONGTEXT NOT NULL, ADD type_espace VARCHAR(255) NOT NULL, DROP listeEquipements, DROP urlImage, DROP typeEspace, CHANGE id id INT NOT NULL, CHANGE disponible disponible TINYINT NOT NULL');
        $this->addSql('DROP INDEX fk_evaluation_candidature ON evaluation_candidat');
        $this->addSql('DROP INDEX fk_evaluation_entretien ON evaluation_candidat');
        $this->addSql('ALTER TABLE evaluation_candidat CHANGE id id INT NOT NULL, CHANGE candidature_externe_id candidature_externe_id INT NOT NULL, CHANGE entretien_id entretien_id INT NOT NULL, CHANGE note_technique note_technique INT NOT NULL, CHANGE note_savoir_etre note_savoir_etre INT NOT NULL, CHANGE note_motivation note_motivation INT NOT NULL, CHANGE note_culture_fit note_culture_fit INT NOT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE recommandation recommandation VARCHAR(50) NOT NULL, CHANGE point_fort point_fort LONGTEXT NOT NULL, CHANGE axe_amelioration axe_amelioration LONGTEXT NOT NULL, CHANGE date_evaluation date_evaluation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE evaluation_question DROP FOREIGN KEY `evaluation_question_ibfk_1`');
        $this->addSql('ALTER TABLE evaluation_question CHANGE id id INT NOT NULL, CHANGE evaluation_id evaluation_id INT DEFAULT NULL, CHANGE question question LONGTEXT NOT NULL, CHANGE option_c option_c VARCHAR(255) NOT NULL, CHANGE option_d option_d VARCHAR(255) NOT NULL, CHANGE bonne_reponse bonne_reponse VARCHAR(1) NOT NULL, CHANGE explication explication LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE evaluation_question ADD CONSTRAINT FK_BBB93068456C5646 FOREIGN KEY (evaluation_id) REFERENCES evaluationformation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_question RENAME INDEX idx_evalq_evaluation TO IDX_BBB93068456C5646');
        $this->addSql('ALTER TABLE evaluationformation DROP FOREIGN KEY `evaluationformation_ibfk_1`');
        $this->addSql('ALTER TABLE evaluationformation ADD date_debut DATE NOT NULL, ADD date_fin DATE NOT NULL, DROP dateDebut, DROP dateFin, CHANGE id id INT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(100) NOT NULL, CHANGE duree duree INT NOT NULL, CHANGE session_id session_id INT DEFAULT NULL, CHANGE score_requis score_requis INT NOT NULL, CHANGE niveau_succes niveau_succes INT NOT NULL, CHANGE niveau_echec niveau_echec INT NOT NULL, CHANGE competence_id competence_id INT NOT NULL, CHANGE niveau_requis niveau_requis INT NOT NULL, CHANGE difficulte difficulte VARCHAR(10) NOT NULL, CHANGE statut_eval statut_eval VARCHAR(10) NOT NULL');
        $this->addSql('ALTER TABLE evaluationformation ADD CONSTRAINT FK_63CE1DF9613FECDF FOREIGN KEY (session_id) REFERENCES sessionformation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluationformation RENAME INDEX idx_evaluation_session TO IDX_63CE1DF9613FECDF');
        $this->addSql('ALTER TABLE evenement ADD date_heure_debut DATETIME NOT NULL, ADD date_heure_fin DATETIME NOT NULL, ADD participants_inscrits LONGTEXT NOT NULL, ADD cree_le DATETIME NOT NULL, DROP dateHeureDebut, DROP dateHeureFin, DROP participantsInscrits, DROP creeLe, CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE dateEvenement date_evenement DATE NOT NULL, CHANGE nbParticipantsMax nb_participants_max INT NOT NULL, CHANGE creePar cree_par VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY `exercice_soumission_ibfk_2`');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY `exercice_soumission_ibfk_3`');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY `fk_exsoum_utilisateur`');
        $this->addSql('ALTER TABLE exercice_soumission CHANGE id id INT NOT NULL, CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE contenu_rendu contenu_rendu LONGTEXT NOT NULL, CHANGE note_ia note_ia INT NOT NULL, CHANGE feedback_ia feedback_ia LONGTEXT NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_soumission date_soumission DATETIME NOT NULL, CHANGE date_correction date_correction DATETIME NOT NULL');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT FK_60E3D0941B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT FK_60E3D094AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT FK_60E3D0943E5BB690 FOREIGN KEY (sous_section_id) REFERENCES module_sous_section (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX idx_soumission_emp TO IDX_60E3D0941B65292');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX idx_soumission_mod TO IDX_60E3D094AFC2B591');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX sous_section_id TO IDX_60E3D0943E5BB690');
        $this->addSql('ALTER TABLE follow DROP FOREIGN KEY `follow_ibfk_1`');
        $this->addSql('ALTER TABLE follow DROP FOREIGN KEY `follow_ibfk_2`');
        $this->addSql('DROP INDEX unique_follow ON follow');
        $this->addSql('ALTER TABLE follow ADD followed_at DATETIME NOT NULL, DROP followedAt, CHANGE id id INT NOT NULL, CHANGE followerId followerId INT DEFAULT NULL, CHANGE followingId followingId INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470F542AA03 FOREIGN KEY (followerId) REFERENCES users (id)');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470CCE76DFF FOREIGN KEY (followingId) REFERENCES users (id)');
        $this->addSql('ALTER TABLE follow RENAME INDEX idx_follow_follower TO IDX_68344470F542AA03');
        $this->addSql('ALTER TABLE follow RENAME INDEX idx_follow_following TO IDX_68344470CCE76DFF');
        $this->addSql('ALTER TABLE formateur CHANGE specialite specialite VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY `formation_ibfk_1`');
        $this->addSql('ALTER TABLE formation ADD statut_formation VARCHAR(100) NOT NULL, ADD type_formation VARCHAR(255) NOT NULL, DROP statutFormation, DROP typeFormation, CHANGE id id INT NOT NULL, CHANGE cout cout DOUBLE PRECISION NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE formateur_id formateur_id INT NOT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BFBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorieformation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE formation RENAME INDEX idx_formation_categorie TO IDX_404021BFBCF5E72D');
        $this->addSql('DROP INDEX unique_member ON groupmember');
        $this->addSql('ALTER TABLE groupmember ADD joined_at DATETIME NOT NULL, DROP joinedAt, CHANGE id id INT NOT NULL, CHANGE groupId groupId INT DEFAULT NULL, CHANGE userId userId INT DEFAULT NULL, CHANGE role role VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE groupmember RENAME INDEX userid TO IDX_AAF03D8364B64DCC');
        $this->addSql('ALTER TABLE `groups` ADD created_at DATETIME NOT NULL, ADD image_url VARCHAR(500) NOT NULL, ADD member_count INT NOT NULL, DROP createdAt, DROP imageUrl, DROP memberCount, CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE createdById createdById INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `groups` RENAME INDEX idx_groups_creator TO IDX_F06D3970774D5986');
        $this->addSql('ALTER TABLE inscriptionformation DROP FOREIGN KEY `fk_insc_utilisateur`');
        $this->addSql('ALTER TABLE inscriptionformation DROP FOREIGN KEY `inscriptionformation_ibfk_1`');
        $this->addSql('ALTER TABLE inscriptionformation ADD date_inscription DATE NOT NULL, ADD note_finale DOUBLE PRECISION NOT NULL, DROP dateInscription, DROP noteFinale, CHANGE id id INT NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL, CHANGE progression progression INT NOT NULL, CHANGE session_id session_id INT DEFAULT NULL, CHANGE employe_id employe_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE inscriptionformation ADD CONSTRAINT FK_C7151B7A613FECDF FOREIGN KEY (session_id) REFERENCES sessionformation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscriptionformation ADD CONSTRAINT FK_C7151B7A1B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscriptionformation RENAME INDEX session_id TO IDX_C7151B7A613FECDF');
        $this->addSql('ALTER TABLE inscriptionformation RENAME INDEX employe_id TO IDX_C7151B7A1B65292');
        $this->addSql('ALTER TABLE module DROP FOREIGN KEY `module_ibfk_1`');
        $this->addSql('ALTER TABLE module CHANGE id id INT NOT NULL, CHANGE formation_id formation_id INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE type_contenu type_contenu VARCHAR(255) NOT NULL, CHANGE duree_minutes duree_minutes INT NOT NULL, CHANGE ordre ordre INT NOT NULL, CHANGE contenu_texte contenu_texte LONGTEXT NOT NULL, CHANGE url_ressource url_ressource VARCHAR(500) NOT NULL');
        $this->addSql('ALTER TABLE module ADD CONSTRAINT FK_C2426285200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module RENAME INDEX idx_module_formation TO IDX_C2426285200282E');
        $this->addSql('DROP INDEX unique_highlight ON module_highlights');
        $this->addSql('DROP INDEX idx_module_inscription ON module_highlights');
        $this->addSql('ALTER TABLE module_highlights CHANGE id id INT NOT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE text_key text_key VARCHAR(255) NOT NULL, CHANGE color color VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_module_inscription ON module_notes');
        $this->addSql('ALTER TABLE module_notes CHANGE id id INT NOT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE note_text note_text LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE module_progression DROP FOREIGN KEY `fk_modprog_utilisateur`');
        $this->addSql('ALTER TABLE module_progression DROP FOREIGN KEY `module_progression_ibfk_2`');
        $this->addSql('DROP INDEX uq_emp_mod ON module_progression');
        $this->addSql('ALTER TABLE module_progression CHANGE id id INT NOT NULL, CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE score_quiz score_quiz INT NOT NULL, CHANGE date_completion date_completion DATE NOT NULL');
        $this->addSql('ALTER TABLE module_progression ADD CONSTRAINT FK_5B995AA11B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_progression ADD CONSTRAINT FK_5B995AA1AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_progression RENAME INDEX idx_progression_employe TO IDX_5B995AA11B65292');
        $this->addSql('ALTER TABLE module_progression RENAME INDEX idx_progression_module TO IDX_5B995AA1AFC2B591');
        $this->addSql('ALTER TABLE module_section DROP FOREIGN KEY `module_section_ibfk_1`');
        $this->addSql('ALTER TABLE module_section CHANGE id id INT NOT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE ordre ordre INT NOT NULL');
        $this->addSql('ALTER TABLE module_section ADD CONSTRAINT FK_860844F6AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_section RENAME INDEX idx_section_module TO IDX_860844F6AFC2B591');
        $this->addSql('ALTER TABLE module_sous_section DROP FOREIGN KEY `module_sous_section_ibfk_1`');
        $this->addSql('ALTER TABLE module_sous_section CHANGE id id INT NOT NULL, CHANGE section_id section_id INT DEFAULT NULL, CHANGE type_contenu type_contenu VARCHAR(255) NOT NULL, CHANGE contenu_texte contenu_texte LONGTEXT NOT NULL, CHANGE url_ressource url_ressource VARCHAR(500) NOT NULL, CHANGE duree_minutes duree_minutes INT NOT NULL, CHANGE ordre ordre INT NOT NULL');
        $this->addSql('ALTER TABLE module_sous_section ADD CONSTRAINT FK_66299A50D823E37A FOREIGN KEY (section_id) REFERENCES module_section (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_sous_section RENAME INDEX idx_soussection_sec TO IDX_66299A50D823E37A');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_2`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_3`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_4`');
        $this->addSql('DROP INDEX idx_notif_seen ON notification');
        $this->addSql('ALTER TABLE notification ADD date_creation DATETIME NOT NULL, ADD date_view_at DATETIME NOT NULL, DROP dateCreation, DROP dateViewAt, CHANGE id id INT NOT NULL, CHANGE message message LONGTEXT NOT NULL, CHANGE userId userId INT DEFAULT NULL, CHANGE seen seen TINYINT NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA99A3424D FOREIGN KEY (relatedUserId) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA4AD5F91 FOREIGN KEY (relatedPublicationId) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA229FA9C7 FOREIGN KEY (relatedCommentaireId) REFERENCES commentaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_notif_user TO IDX_BF5476CA64B64DCC');
        $this->addSql('ALTER TABLE notification RENAME INDEX relateduserid TO IDX_BF5476CA99A3424D');
        $this->addSql('ALTER TABLE notification RENAME INDEX relatedpublicationid TO IDX_BF5476CA4AD5F91');
        $this->addSql('ALTER TABLE notification RENAME INDEX relatedcommentaireid TO IDX_BF5476CA229FA9C7');
        $this->addSql('ALTER TABLE participation_evenement ADD id_employe INT NOT NULL, ADD cree_le DATETIME NOT NULL, DROP idEmploye, DROP creeLe, CHANGE id id INT NOT NULL, CHANGE idEvenement idEvenement INT DEFAULT NULL, CHANGE dateParticipation date_participation DATE NOT NULL');
        $this->addSql('ALTER TABLE participation_evenement RENAME INDEX fk_participation_evenement TO IDX_65A14675F7CC4348');
        $this->addSql('ALTER TABLE pdi DROP FOREIGN KEY `fk_pdi_employe`');
        $this->addSql('ALTER TABLE pdi DROP FOREIGN KEY `fk_pdi_utilisateur`');
        $this->addSql('ALTER TABLE pdi ADD progression_globale INT NOT NULL, ADD date_creation DATE NOT NULL, DROP progressionGlobale, DROP dateCreation, CHANGE id id INT NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE pdi ADD CONSTRAINT FK_9E4FC61D1B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pdi RENAME INDEX fk_pdi_utilisateur TO IDX_9E4FC61D1B65292');
        $this->addSql('DROP INDEX fk_pipeline_poste ON pipeline_etape');
        $this->addSql('ALTER TABLE pipeline_etape CHANGE id id INT NOT NULL, CHANGE poste_externe_id poste_externe_id INT NOT NULL, CHANGE ordre ordre INT NOT NULL, CHANGE libelle libelle VARCHAR(100) NOT NULL, CHANGE description_etape description_etape LONGTEXT NOT NULL, CHANGE duree_moyenne duree_moyenne INT NOT NULL, CHANGE action_automatique action_automatique VARCHAR(100) NOT NULL, CHANGE obligatoire obligatoire TINYINT NOT NULL');
        $this->addSql('ALTER TABLE poll ADD created_at DATETIME NOT NULL, ADD closed_at DATETIME NOT NULL, ADD total_votes INT NOT NULL, ADD expires_at DATETIME NOT NULL, ADD is_anonymous TINYINT NOT NULL, ADD allow_multiple TINYINT NOT NULL, ADD created_by_id INT NOT NULL, DROP createdAt, DROP closedAt, DROP totalVotes, DROP expiresAt, DROP isAnonymous, DROP allowMultiple, DROP createdById, CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE poll RENAME INDEX publicationid TO IDX_84BCFA45796DA8A');
        $this->addSql('DROP INDEX pollId ON poll_option');
        $this->addSql('ALTER TABLE poll_option ADD vote_count INT NOT NULL, ADD option_order INT NOT NULL, DROP voteCount, DROP optionOrder, CHANGE id id INT NOT NULL, CHANGE pollId poll_id INT NOT NULL, CHANGE optionText option_text VARCHAR(200) NOT NULL');
        $this->addSql('DROP INDEX unique_vote ON poll_vote');
        $this->addSql('DROP INDEX optionId ON poll_vote');
        $this->addSql('ALTER TABLE poll_vote ADD poll_id INT NOT NULL, ADD option_id INT NOT NULL, ADD user_id INT NOT NULL, ADD voted_at DATETIME NOT NULL, DROP pollId, DROP optionId, DROP userId, DROP votedAt, CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE poste_externe CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE type_contrat type_contrat VARCHAR(50) NOT NULL, CHANGE salaire salaire DOUBLE PRECISION NOT NULL, CHANGE competences_requises competences_requises LONGTEXT NOT NULL, CHANGE experience_requise experience_requise INT NOT NULL, CHANGE niveau_etude_requis niveau_etude_requis VARCHAR(50) NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE date_publication date_publication DATE NOT NULL, CHANGE date_cloture date_cloture DATE NOT NULL, CHANGE nombre_employe nombre_employe INT NOT NULL, CHANGE priorite priorite INT NOT NULL');
        $this->addSql('ALTER TABLE poste_interne CHANGE id id INT NOT NULL, CHANGE date_fin date_fin DATE NOT NULL');
        $this->addSql('DROP INDEX idx_pub_date ON publication');
        $this->addSql('DROP INDEX idx_pub_statut ON publication');
        $this->addSql('ALTER TABLE publication CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE authorId authorId INT DEFAULT NULL, CHANGE dateCreation dateCreation DATETIME NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE nombreCommentaires nombreCommentaires INT NOT NULL, CHANGE nombreReactions nombreReactions INT NOT NULL, CHANGE visibility visibility VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_pub_author TO IDX_AF3C6779A196F9FD');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_pub_shared TO IDX_AF3C6779D7A914D7');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_publication_group TO IDX_AF3C6779ED8188B0');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY `quiz_question_ibfk_1`');
        $this->addSql('ALTER TABLE quiz_question CHANGE id id INT NOT NULL, CHANGE module_id module_id INT DEFAULT NULL, CHANGE question question LONGTEXT NOT NULL, CHANGE option_c option_c VARCHAR(255) NOT NULL, CHANGE option_d option_d VARCHAR(255) NOT NULL, CHANGE bonne_reponse bonne_reponse VARCHAR(1) NOT NULL, CHANGE explication explication LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00BAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question RENAME INDEX idx_quiz_module TO IDX_6033B00BAFC2B591');
        $this->addSql('DROP INDEX unique_reaction_pub ON reaction');
        $this->addSql('DROP INDEX unique_reaction_comment ON reaction');
        $this->addSql('ALTER TABLE reaction CHANGE type type VARCHAR(255) NOT NULL, CHANGE userId userId INT DEFAULT NULL, CHANGE dateCreation dateCreation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_reaction_user TO IDX_A4D707F764B64DCC');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_reaction_pub TO IDX_A4D707F7796DA8A');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_reaction_comment TO IDX_A4D707F721A42CDC');
        $this->addSql('DROP INDEX chair_id ON reservation');
        $this->addSql('ALTER TABLE reservation CHANGE id id INT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE chair_id chair_id INT NOT NULL, CHANGE reservation_date reservation_date DATE NOT NULL, CHANGE status status VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE reservation_espaces ADD id_employe INT NOT NULL, ADD date_heure_debut DATETIME NOT NULL, ADD date_heure_fin DATETIME NOT NULL, ADD cree_le DATETIME NOT NULL, DROP idEmploye, DROP dateHeureDebut, DROP dateHeureFin, DROP creeLe, CHANGE id id INT NOT NULL, CHANGE idEspace idEspace INT DEFAULT NULL, CHANGE objectif objectif VARCHAR(255) NOT NULL, CHANGE statut statut TINYINT NOT NULL, CHANGE dateReservation date_reservation DATE NOT NULL');
        $this->addSql('ALTER TABLE reservation_espaces RENAME INDEX fk_reservation_space TO IDX_4F9EC26265BAA1F7');
        $this->addSql('ALTER TABLE resultatevaluation DROP FOREIGN KEY `fk_resultat_utilisateur`');
        $this->addSql('ALTER TABLE resultatevaluation DROP FOREIGN KEY `fk_resultatEvaluation_employe`');
        $this->addSql('ALTER TABLE resultatevaluation DROP FOREIGN KEY `resultatevaluation_ibfk_1`');
        $this->addSql('ALTER TABLE resultatevaluation ADD date_passage DATE NOT NULL, DROP datePassage, CHANGE id id INT NOT NULL, CHANGE note note DOUBLE PRECISION NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL, CHANGE commentaire commentaire VARCHAR(255) NOT NULL, CHANGE evaluation_id evaluation_id INT DEFAULT NULL, CHANGE score_pct score_pct INT NOT NULL, CHANGE niveau_delta niveau_delta INT NOT NULL');
        $this->addSql('ALTER TABLE resultatevaluation ADD CONSTRAINT FK_3E592CCB456C5646 FOREIGN KEY (evaluation_id) REFERENCES evaluationformation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultatevaluation ADD CONSTRAINT FK_3E592CCB1B65292 FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultatevaluation RENAME INDEX idx_resultat_evaluation TO IDX_3E592CCB456C5646');
        $this->addSql('ALTER TABLE resultatevaluation RENAME INDEX fk_resultat_utilisateur TO IDX_3E592CCB1B65292');
        $this->addSql('ALTER TABLE reunion ADD date_heure_debut DATETIME NOT NULL, ADD date_heure_fin DATETIME NOT NULL, ADD nom_organisateur VARCHAR(255) NOT NULL, ADD email_organisateur VARCHAR(255) NOT NULL, ADD en_ligne TINYINT NOT NULL, ADD cree_le DATETIME NOT NULL, DROP dateHeureDebut, DROP dateHeureFin, DROP nomOrganisateur, DROP emailOrganisateur, DROP enLigne, DROP creeLe, CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE idSalle idSalle INT DEFAULT NULL, CHANGE participants participants LONGTEXT NOT NULL, CHANGE statut statut TINYINT NOT NULL, CHANGE zoom_meeting_id zoom_meeting_id BIGINT NOT NULL, CHANGE zoom_join_url zoom_join_url VARCHAR(512) NOT NULL, CHANGE zoom_start_url zoom_start_url VARCHAR(512) NOT NULL, CHANGE zoom_password zoom_password VARCHAR(64) NOT NULL');
        $this->addSql('ALTER TABLE reunion RENAME INDEX fk_reunion_room TO IDX_5B00A48259533D41');
        $this->addSql('DROP INDEX unique_saved ON savedpost');
        $this->addSql('ALTER TABLE savedpost CHANGE userId userId INT DEFAULT NULL, CHANGE publicationId publicationId INT DEFAULT NULL, CHANGE savedAt savedAt DATETIME NOT NULL');
        $this->addSql('ALTER TABLE savedpost RENAME INDEX idx_saved_user TO IDX_F39B527F64B64DCC');
        $this->addSql('ALTER TABLE savedpost RENAME INDEX idx_saved_pub TO IDX_F39B527F796DA8A');
        $this->addSql('ALTER TABLE sessionformation DROP FOREIGN KEY `sessionformation_ibfk_1`');
        $this->addSql('ALTER TABLE sessionformation ADD date_debut DATE NOT NULL, ADD date_fin DATE NOT NULL, DROP dateDebut, DROP dateFin, CHANGE id id INT NOT NULL, CHANGE lieu lieu VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL, CHANGE formation_id formation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sessionformation ADD CONSTRAINT FK_E52C04B75200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sessionformation RENAME INDEX idx_session_formation TO IDX_E52C04B75200282E');
        $this->addSql('DROP INDEX idx_share_sharedAt ON share');
        $this->addSql('ALTER TABLE share CHANGE userId userId INT DEFAULT NULL, CHANGE publicationId publicationId INT DEFAULT NULL, CHANGE shareCount shareCount INT NOT NULL');
        $this->addSql('ALTER TABLE share ADD CONSTRAINT FK_EF069D5A64B64DCC FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE share ADD CONSTRAINT FK_EF069D5A796DA8A FOREIGN KEY (publicationId) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE share RENAME INDEX idx_share_userid TO IDX_EF069D5A64B64DCC');
        $this->addSql('ALTER TABLE share RENAME INDEX idx_share_publicationid TO IDX_EF069D5A796DA8A');
        $this->addSql('ALTER TABLE sous_section_progression DROP FOREIGN KEY `fk_ssprog_utilisateur`');
        $this->addSql('ALTER TABLE sous_section_progression DROP FOREIGN KEY `sous_section_progression_ibfk_1`');
        $this->addSql('ALTER TABLE sous_section_progression DROP FOREIGN KEY `sous_section_progression_ibfk_2`');
        $this->addSql('DROP INDEX uq_emp_ss ON sous_section_progression');
        $this->addSql('ALTER TABLE sous_section_progression CHANGE id id INT NOT NULL, CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE sous_section_id sous_section_id INT DEFAULT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE date_completion date_completion DATETIME NOT NULL');
        $this->addSql('ALTER TABLE sous_section_progression ADD CONSTRAINT FK_6E07BF081B65292 FOREIGN KEY (employe_id) REFERENCES employe_competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sous_section_progression ADD CONSTRAINT FK_6E07BF083E5BB690 FOREIGN KEY (sous_section_id) REFERENCES module_sous_section (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sous_section_progression RENAME INDEX idx_ssprog_emp TO IDX_6E07BF081B65292');
        $this->addSql('ALTER TABLE sous_section_progression RENAME INDEX sous_section_id TO IDX_6E07BF083E5BB690');
        $this->addSql('ALTER TABLE type_absence CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE type_conge CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE userprofile DROP INDEX userId, ADD INDEX IDX_1D3656B164B64DCC (userId)');
        $this->addSql('ALTER TABLE userprofile ADD avatar_url VARCHAR(500) NOT NULL, ADD cover_url VARCHAR(500) NOT NULL, ADD job_title VARCHAR(100) NOT NULL, ADD followers_count INT NOT NULL, ADD following_count INT NOT NULL, ADD posts_count INT NOT NULL, DROP avatarUrl, DROP coverUrl, DROP jobTitle, DROP followersCount, DROP followingCount, DROP postsCount, CHANGE id id INT NOT NULL, CHANGE userId userId INT DEFAULT NULL, CHANGE bio bio LONGTEXT NOT NULL, CHANGE location location VARCHAR(100) NOT NULL, CHANGE website website VARCHAR(200) NOT NULL, CHANGE company company VARCHAR(100) NOT NULL');
        $this->addSql('DROP INDEX username ON users');
        $this->addSql('DROP INDEX email ON users');
        $this->addSql('DROP INDEX idx_users_username ON users');
        $this->addSql('DROP INDEX idx_users_email ON users');
        $this->addSql('ALTER TABLE users CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE createdAt createdAt DATETIME NOT NULL, CHANGE updatedAt updatedAt DATETIME NOT NULL, CHANGE isActive isActive TINYINT NOT NULL, CHANGE role role VARCHAR(20) NOT NULL, CHANGE isOnline isOnline TINYINT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role ENUM(\'ADMIN\',\'EMPLOYE\',\'MANAGER\',\'RH\',\'FORMATEUR\',\'CANDIDAT\'), CHANGE statut statut ENUM(\'Archive\',\'Actif\',\'Inactif\',\'bloque\',\'sus\'), CHANGE date_creation date_creation DATETIME DEFAULT NULL, CHANGE donnees_faciales donnees_faciales LONGBLOB DEFAULT NULL, CHANGE mfa_enabled mfa_enabled TINYINT DEFAULT NULL, CHANGE is_online is_online TINYINT DEFAULT NULL, CHANGE posteActuel poste_actuel VARCHAR(150) DEFAULT NULL, CHANGE dateEmbauche date_embauche DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX email TO UNIQ_1D1C63B3E7927C74');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX username TO UNIQ_1D1C63B3F85E0677');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX fk_manager TO IDX_1D1C63B3783E3463');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE absence CHANGE statut statut VARCHAR(50) DEFAULT \'En attente\', CHANGE heure_debut heure_debut VARCHAR(5) DEFAULT NULL COMMENT \'Format HH:MM\', CHANGE heure_fin heure_fin VARCHAR(5) DEFAULT NULL COMMENT \'Format HH:MM\', CHANGE duree_minutes duree_minutes INT DEFAULT NULL COMMENT \'Durée en minutes\', CHANGE motif motif VARCHAR(255) DEFAULT NULL COMMENT \'Motif de la demande\'');
        $this->addSql('CREATE INDEX type_absence_id ON absence (type_absence_id)');
        $this->addSql('CREATE INDEX fk_absence_user ON absence (utilisateur_id)');
        $this->addSql('ALTER TABLE actionpdi DROP FOREIGN KEY FK_653CF31897CD944');
        $this->addSql('ALTER TABLE actionpdi DROP FOREIGN KEY FK_653CF3185200282E');
        $this->addSql('ALTER TABLE actionpdi ADD typeAction VARCHAR(100) DEFAULT NULL, ADD dateDebut DATE DEFAULT NULL, ADD dateFinPrevue DATE DEFAULT NULL, DROP type_action, DROP date_debut, DROP date_fin_prevue, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut VARCHAR(100) DEFAULT NULL, CHANGE priorite priorite INT DEFAULT NULL, CHANGE pdi_id pdi_id INT NOT NULL');
        $this->addSql('ALTER TABLE actionpdi ADD CONSTRAINT `actionpdi_ibfk_1` FOREIGN KEY (pdi_id) REFERENCES pdi (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE actionpdi ADD CONSTRAINT `fk_actionPDI_formation` FOREIGN KEY (formation_id) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE actionpdi RENAME INDEX idx_653cf31897cd944 TO idx_action_pdi');
        $this->addSql('ALTER TABLE actionpdi RENAME INDEX idx_653cf3185200282e TO idx_action_formation');
        $this->addSql('ALTER TABLE candidature CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE poste_interne_id poste_interne_id INT DEFAULT NULL, CHANGE candidat_id candidat_id INT DEFAULT NULL, CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE type_candidat type_candidat VARCHAR(50) DEFAULT NULL, CHANGE date_depot date_depot DATE DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE etape_pipeline etape_pipeline VARCHAR(50) DEFAULT NULL, CHANGE scoring_ia scoring_ia DOUBLE PRECISION DEFAULT NULL, CHANGE cv_url cv_url VARCHAR(255) DEFAULT NULL, CHANGE lettre_motivation_url lettre_motivation_url VARCHAR(255) DEFAULT NULL, CHANGE derniere_modification derniere_modification DATE DEFAULT NULL, CHANGE commentaires_rh commentaires_rh TEXT DEFAULT NULL, CHANGE salaire_pretendu salaire_pretendu DOUBLE PRECISION DEFAULT NULL, CHANGE nom nom VARCHAR(100) DEFAULT NULL, CHANGE prenom prenom VARCHAR(100) DEFAULT NULL, CHANGE email email VARCHAR(100) DEFAULT NULL');
        $this->addSql('CREATE INDEX fk_candidature_poste ON candidature (poste_interne_id)');
        $this->addSql('ALTER TABLE candidature_externe CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'EN_ATTENTE\', CHANGE etape_pipeline etape_pipeline VARCHAR(50) DEFAULT NULL, CHANGE scoring_ia scoring_ia DOUBLE PRECISION DEFAULT NULL, CHANGE cv_url cv_url VARCHAR(255) DEFAULT NULL, CHANGE lettre_motivation_url lettre_motivation_url VARCHAR(255) DEFAULT NULL, CHANGE derniere_modification derniere_modification DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX fk_candidature_poste ON candidature_externe (poste_externe_id)');
        $this->addSql('ALTER TABLE candidature_interne CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nouveau_salaire nouveau_salaire DOUBLE PRECISION DEFAULT NULL, CHANGE motif motif TEXT DEFAULT NULL, CHANGE derniere_modification derniere_modification DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE categoriecompetence CHANGE couleur couleur VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE categorieformation CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE couleur couleur VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE chaise CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE espace_id espace_id INT DEFAULT NULL, CHANGE chair_number chair_number INT DEFAULT NULL');
        $this->addSql('CREATE INDEX espace_id ON chaise (espace_id)');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu TEXT NOT NULL, CHANGE dateCreation dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE statut statut ENUM(\'ACTIF\', \'SUPPRIME\', \'ARCHIVE\') DEFAULT \'ACTIF\', CHANGE nombreReactions nombreReactions INT DEFAULT 0, CHANGE publicationId publicationId INT NOT NULL, CHANGE authorId authorId INT NOT NULL');
        $this->addSql('ALTER TABLE commentaire RENAME INDEX idx_67f068bc796da8a TO idx_comment_pub');
        $this->addSql('ALTER TABLE commentaire RENAME INDEX idx_67f068bca196f9fd TO idx_comment_author');
        $this->addSql('ALTER TABLE competence DROP FOREIGN KEY FK_94D4687FBCF5E72D');
        $this->addSql('ALTER TABLE competence CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE typeCompetence typeCompetence VARCHAR(100) DEFAULT NULL, CHANGE statutCompetence statutCompetence VARCHAR(50) DEFAULT \'ACTIF\' NOT NULL');
        $this->addSql('ALTER TABLE competence ADD CONSTRAINT `competence_ibfk_1` FOREIGN KEY (categorie_id) REFERENCES categoriecompetence (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE competence RENAME INDEX idx_94d4687fbcf5e72d TO categorie_id');
        $this->addSql('ALTER TABLE competence_niveau_history CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE INDEX idx_emp_comp ON competence_niveau_history (employe_id, competence_id)');
        $this->addSql('ALTER TABLE competenceemploye DROP FOREIGN KEY FK_48D451261B65292');
        $this->addSql('ALTER TABLE competenceemploye DROP FOREIGN KEY FK_48D4512615761DAB');
        $this->addSql('ALTER TABLE competenceemploye ADD niveauValide TINYINT DEFAULT 0, ADD preuveUrl VARCHAR(255) DEFAULT NULL, ADD dateEvaluation DATE DEFAULT NULL, DROP niveau_valide, DROP preuve_url, DROP date_evaluation, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE employe_id employe_id INT NOT NULL, CHANGE competence_id competence_id INT NOT NULL, CHANGE niveau_actuel niveauActuel INT NOT NULL');
        $this->addSql('ALTER TABLE competenceemploye ADD CONSTRAINT `fk_ce_competence` FOREIGN KEY (competence_id) REFERENCES competence (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE competenceemploye ADD CONSTRAINT `fk_ce_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_employe_competence ON competenceemploye (employe_id, competence_id)');
        $this->addSql('ALTER TABLE competenceemploye RENAME INDEX idx_48d451261b65292 TO employe_id');
        $this->addSql('ALTER TABLE competenceemploye RENAME INDEX idx_48d4512615761dab TO competence_id');
        $this->addSql('ALTER TABLE conge CHANGE statut statut VARCHAR(50) DEFAULT \'En attente\'');
        $this->addSql('CREATE INDEX type_conge_id ON conge (type_conge_id)');
        $this->addSql('CREATE INDEX fk_conge_user ON conge (utilisateur_id)');
        $this->addSql('ALTER TABLE coworking_reservations CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uq_espace_chair_date ON coworking_reservations (espace_id, chair_number, reservation_date)');
        $this->addSql('ALTER TABLE demande_absence CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE motif motif TEXT DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'En attente\'');
        $this->addSql('CREATE INDEX absence_id ON demande_absence (absence_id)');
        $this->addSql('ALTER TABLE demande_conge CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE motif motif TEXT DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'En attente\'');
        $this->addSql('CREATE INDEX conge_id ON demande_conge (conge_id)');
        $this->addSql('ALTER TABLE document CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE uploaded_at uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE employe CHANGE matricule matricule VARCHAR(50) DEFAULT NULL, CHANGE poste_actuel poste_actuel VARCHAR(100) DEFAULT NULL, CHANGE date_embauche date_embauche DATE DEFAULT NULL, CHANGE departement departement VARCHAR(100) DEFAULT NULL, CHANGE manager_id manager_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX matricule ON employe (matricule)');
        $this->addSql('CREATE INDEX manager_id ON employe (manager_id)');
        $this->addSql('ALTER TABLE employe_competence ADD posteActuel VARCHAR(255) DEFAULT NULL, ADD dateEmbauche DATE DEFAULT NULL, DROP poste_actuel, DROP date_embauche, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE departement Departement VARCHAR(255) DEFAULT NULL, CHANGE nom nom VARCHAR(50) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX matricule ON employe_competence (matricule)');
        $this->addSql('CREATE INDEX idx_employe_matricule ON employe_competence (matricule)');
        $this->addSql('CREATE INDEX idx_employe_departement ON employe_competence (Departement)');
        $this->addSql('ALTER TABLE entretien_recrutement CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE candidature_externe_id candidature_externe_id INT DEFAULT NULL, CHANGE type_entretien type_entretien VARCHAR(50) DEFAULT NULL, CHANGE date_entretien date_entretien DATE DEFAULT NULL, CHANGE heure_debut heure_debut TIME DEFAULT NULL, CHANGE heure_fin heure_fin TIME DEFAULT NULL, CHANGE intervieweurs_ids intervieweurs_ids TEXT DEFAULT NULL, CHANGE salle salle VARCHAR(50) DEFAULT NULL, CHANGE url_visio url_visio VARCHAR(255) DEFAULT NULL, CHANGE statut_entretien statut_entretien VARCHAR(50) DEFAULT NULL, CHANGE note_entretien note_entretien DOUBLE PRECISION DEFAULT NULL, CHANGE duree duree INT DEFAULT NULL');
        $this->addSql('CREATE INDEX fk_entretien_candidature ON entretien_recrutement (candidature_externe_id)');
        $this->addSql('ALTER TABLE equipement CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX nom ON equipement (nom)');
        $this->addSql('ALTER TABLE espaces ADD listeEquipements LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, ADD urlImage TEXT DEFAULT NULL, ADD typeEspace ENUM(\'REUNION\', \'COWORKING\') NOT NULL, DROP liste_equipements, DROP url_image, DROP type_espace, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE disponible disponible TINYINT DEFAULT 1');
        $this->addSql('ALTER TABLE evaluation_candidat CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE candidature_externe_id candidature_externe_id INT DEFAULT NULL, CHANGE entretien_id entretien_id INT DEFAULT NULL, CHANGE note_technique note_technique INT DEFAULT NULL, CHANGE note_savoir_etre note_savoir_etre INT DEFAULT NULL, CHANGE note_motivation note_motivation INT DEFAULT NULL, CHANGE note_culture_fit note_culture_fit INT DEFAULT NULL, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE recommandation recommandation VARCHAR(50) DEFAULT NULL, CHANGE point_fort point_fort TEXT DEFAULT NULL, CHANGE axe_amelioration axe_amelioration TEXT DEFAULT NULL, CHANGE date_evaluation date_evaluation DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX fk_evaluation_candidature ON evaluation_candidat (candidature_externe_id)');
        $this->addSql('CREATE INDEX fk_evaluation_entretien ON evaluation_candidat (entretien_id)');
        $this->addSql('ALTER TABLE evaluation_question DROP FOREIGN KEY FK_BBB93068456C5646');
        $this->addSql('ALTER TABLE evaluation_question CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE question question TEXT NOT NULL, CHANGE option_c option_c VARCHAR(255) DEFAULT NULL, CHANGE option_d option_d VARCHAR(255) DEFAULT NULL, CHANGE bonne_reponse bonne_reponse CHAR(1) NOT NULL, CHANGE explication explication TEXT DEFAULT NULL, CHANGE evaluation_id evaluation_id INT NOT NULL');
        $this->addSql('ALTER TABLE evaluation_question ADD CONSTRAINT `evaluation_question_ibfk_1` FOREIGN KEY (evaluation_id) REFERENCES evaluationformation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_question RENAME INDEX idx_bbb93068456c5646 TO idx_evalq_evaluation');
        $this->addSql('ALTER TABLE evaluationformation DROP FOREIGN KEY FK_63CE1DF9613FECDF');
        $this->addSql('ALTER TABLE evaluationformation ADD dateDebut DATE DEFAULT NULL, ADD dateFin DATE DEFAULT NULL, DROP date_debut, DROP date_fin, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE duree duree INT DEFAULT NULL, CHANGE score_requis score_requis INT DEFAULT 70, CHANGE niveau_succes niveau_succes INT DEFAULT 1, CHANGE niveau_echec niveau_echec INT DEFAULT -1, CHANGE competence_id competence_id INT DEFAULT NULL, CHANGE niveau_requis niveau_requis INT DEFAULT 0, CHANGE difficulte difficulte VARCHAR(10) DEFAULT \'MOYEN\', CHANGE statut_eval statut_eval VARCHAR(10) DEFAULT \'ACTIVE\', CHANGE session_id session_id INT NOT NULL');
        $this->addSql('ALTER TABLE evaluationformation ADD CONSTRAINT `evaluationformation_ibfk_1` FOREIGN KEY (session_id) REFERENCES sessionformation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluationformation RENAME INDEX idx_63ce1df9613fecdf TO idx_evaluation_session');
        $this->addSql('ALTER TABLE evenement ADD dateHeureDebut DATETIME NOT NULL, ADD dateHeureFin DATETIME NOT NULL, ADD participantsInscrits LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, ADD creeLe DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, DROP date_heure_debut, DROP date_heure_fin, DROP participants_inscrits, DROP cree_le, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE date_evenement dateEvenement DATE NOT NULL, CHANGE nb_participants_max nbParticipantsMax INT NOT NULL, CHANGE cree_par creePar VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY FK_60E3D0941B65292');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY FK_60E3D094AFC2B591');
        $this->addSql('ALTER TABLE exercice_soumission DROP FOREIGN KEY FK_60E3D0943E5BB690');
        $this->addSql('ALTER TABLE exercice_soumission CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE contenu_rendu contenu_rendu TEXT NOT NULL, CHANGE note_ia note_ia INT DEFAULT NULL, CHANGE feedback_ia feedback_ia TEXT DEFAULT NULL, CHANGE statut statut ENUM(\'soumis\', \'corrige\', \'en_attente\') DEFAULT \'soumis\', CHANGE date_soumission date_soumission DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE date_correction date_correction DATETIME DEFAULT NULL, CHANGE employe_id employe_id INT NOT NULL, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT `exercice_soumission_ibfk_2` FOREIGN KEY (module_id) REFERENCES module (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT `exercice_soumission_ibfk_3` FOREIGN KEY (sous_section_id) REFERENCES module_sous_section (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE exercice_soumission ADD CONSTRAINT `fk_exsoum_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX idx_60e3d0943e5bb690 TO sous_section_id');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX idx_60e3d0941b65292 TO idx_soumission_emp');
        $this->addSql('ALTER TABLE exercice_soumission RENAME INDEX idx_60e3d094afc2b591 TO idx_soumission_mod');
        $this->addSql('ALTER TABLE follow DROP FOREIGN KEY FK_68344470F542AA03');
        $this->addSql('ALTER TABLE follow DROP FOREIGN KEY FK_68344470CCE76DFF');
        $this->addSql('ALTER TABLE follow ADD followedAt DATETIME DEFAULT CURRENT_TIMESTAMP, DROP followed_at, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE status status ENUM(\'ACTIVE\', \'PENDING\') DEFAULT \'ACTIVE\' NOT NULL, CHANGE followerId followerId INT NOT NULL, CHANGE followingId followingId INT NOT NULL');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT `follow_ibfk_1` FOREIGN KEY (followerId) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT `follow_ibfk_2` FOREIGN KEY (followingId) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX unique_follow ON follow (followerId, followingId)');
        $this->addSql('ALTER TABLE follow RENAME INDEX idx_68344470f542aa03 TO idx_follow_follower');
        $this->addSql('ALTER TABLE follow RENAME INDEX idx_68344470cce76dff TO idx_follow_following');
        $this->addSql('ALTER TABLE formateur CHANGE specialite specialite VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BFBCF5E72D');
        $this->addSql('ALTER TABLE formation ADD statutFormation VARCHAR(100) DEFAULT NULL, ADD typeFormation ENUM(\'CLASSROOM\', \'E_LEARNING\', \'BLENDED\', \'COACHING\', \'MENTORING\') DEFAULT NULL, DROP statut_formation, DROP type_formation, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE cout cout DOUBLE PRECISION DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE formateur_id formateur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT `formation_ibfk_1` FOREIGN KEY (categorie_id) REFERENCES categorieformation (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE formation RENAME INDEX idx_404021bfbcf5e72d TO idx_formation_categorie');
        $this->addSql('ALTER TABLE groupmember ADD joinedAt DATETIME DEFAULT CURRENT_TIMESTAMP, DROP joined_at, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE role role VARCHAR(20) DEFAULT \'MEMBER\', CHANGE groupId groupId INT NOT NULL, CHANGE userId userId INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_member ON groupmember (groupId, userId)');
        $this->addSql('ALTER TABLE groupmember RENAME INDEX idx_aaf03d8364b64dcc TO userId');
        $this->addSql('ALTER TABLE `groups` ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, ADD imageUrl VARCHAR(500) DEFAULT NULL, ADD memberCount INT DEFAULT 0, DROP created_at, DROP image_url, DROP member_count, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE createdById createdById INT NOT NULL');
        $this->addSql('ALTER TABLE `groups` RENAME INDEX idx_f06d3970774d5986 TO idx_groups_creator');
        $this->addSql('ALTER TABLE inscriptionformation DROP FOREIGN KEY FK_C7151B7A613FECDF');
        $this->addSql('ALTER TABLE inscriptionformation DROP FOREIGN KEY FK_C7151B7A1B65292');
        $this->addSql('ALTER TABLE inscriptionformation ADD dateInscription DATE DEFAULT NULL, ADD noteFinale DOUBLE PRECISION DEFAULT \'0\', DROP date_inscription, DROP note_finale, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut VARCHAR(100) DEFAULT \'In Progress\' NOT NULL, CHANGE progression progression INT DEFAULT 0 NOT NULL, CHANGE session_id session_id INT NOT NULL, CHANGE employe_id employe_id INT NOT NULL');
        $this->addSql('ALTER TABLE inscriptionformation ADD CONSTRAINT `fk_insc_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscriptionformation ADD CONSTRAINT `inscriptionformation_ibfk_1` FOREIGN KEY (session_id) REFERENCES sessionformation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscriptionformation RENAME INDEX idx_c7151b7a613fecdf TO session_id');
        $this->addSql('ALTER TABLE inscriptionformation RENAME INDEX idx_c7151b7a1b65292 TO employe_id');
        $this->addSql('ALTER TABLE module DROP FOREIGN KEY FK_C2426285200282E');
        $this->addSql('ALTER TABLE module CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE type_contenu type_contenu ENUM(\'video\', \'reading\', \'exercise\', \'quiz\') DEFAULT \'video\', CHANGE duree_minutes duree_minutes INT DEFAULT 30, CHANGE ordre ordre INT DEFAULT 1, CHANGE contenu_texte contenu_texte TEXT DEFAULT NULL, CHANGE url_ressource url_ressource VARCHAR(500) DEFAULT NULL, CHANGE formation_id formation_id INT NOT NULL');
        $this->addSql('ALTER TABLE module ADD CONSTRAINT `module_ibfk_1` FOREIGN KEY (formation_id) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module RENAME INDEX idx_c2426285200282e TO idx_module_formation');
        $this->addSql('ALTER TABLE module_highlights CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE text_key text_key VARCHAR(255) NOT NULL COMMENT \'First 50 chars of highlighted text\', CHANGE color color VARCHAR(20) NOT NULL COMMENT \'Hex color code\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_highlight ON module_highlights (module_id, inscription_id, text_key)');
        $this->addSql('CREATE INDEX idx_module_inscription ON module_highlights (module_id, inscription_id)');
        $this->addSql('ALTER TABLE module_notes CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE note_text note_text TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('CREATE INDEX idx_module_inscription ON module_notes (module_id, inscription_id)');
        $this->addSql('ALTER TABLE module_progression DROP FOREIGN KEY FK_5B995AA11B65292');
        $this->addSql('ALTER TABLE module_progression DROP FOREIGN KEY FK_5B995AA1AFC2B591');
        $this->addSql('ALTER TABLE module_progression CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut ENUM(\'not_started\', \'in_progress\', \'completed\') DEFAULT \'not_started\', CHANGE score_quiz score_quiz INT DEFAULT NULL, CHANGE date_completion date_completion DATE DEFAULT NULL, CHANGE employe_id employe_id INT NOT NULL, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('ALTER TABLE module_progression ADD CONSTRAINT `fk_modprog_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_progression ADD CONSTRAINT `module_progression_ibfk_2` FOREIGN KEY (module_id) REFERENCES module (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_emp_mod ON module_progression (employe_id, module_id)');
        $this->addSql('ALTER TABLE module_progression RENAME INDEX idx_5b995aa11b65292 TO idx_progression_employe');
        $this->addSql('ALTER TABLE module_progression RENAME INDEX idx_5b995aa1afc2b591 TO idx_progression_module');
        $this->addSql('ALTER TABLE module_section DROP FOREIGN KEY FK_860844F6AFC2B591');
        $this->addSql('ALTER TABLE module_section CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE ordre ordre INT DEFAULT 1, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('ALTER TABLE module_section ADD CONSTRAINT `module_section_ibfk_1` FOREIGN KEY (module_id) REFERENCES module (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_section RENAME INDEX idx_860844f6afc2b591 TO idx_section_module');
        $this->addSql('ALTER TABLE module_sous_section DROP FOREIGN KEY FK_66299A50D823E37A');
        $this->addSql('ALTER TABLE module_sous_section CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type_contenu type_contenu ENUM(\'text\', \'video\', \'pdf\', \'image\', \'exercice\', \'quiz_embed\') DEFAULT \'text\', CHANGE contenu_texte contenu_texte TEXT DEFAULT NULL, CHANGE url_ressource url_ressource VARCHAR(500) DEFAULT NULL, CHANGE duree_minutes duree_minutes INT DEFAULT 5, CHANGE ordre ordre INT DEFAULT 1, CHANGE section_id section_id INT NOT NULL');
        $this->addSql('ALTER TABLE module_sous_section ADD CONSTRAINT `module_sous_section_ibfk_1` FOREIGN KEY (section_id) REFERENCES module_section (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module_sous_section RENAME INDEX idx_66299a50d823e37a TO idx_soussection_sec');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA99A3424D');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA4AD5F91');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA229FA9C7');
        $this->addSql('ALTER TABLE notification ADD dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, ADD dateViewAt DATETIME DEFAULT NULL, DROP date_creation, DROP date_view_at, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE message message TEXT NOT NULL, CHANGE seen seen TINYINT DEFAULT 0, CHANGE userId userId INT NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_2` FOREIGN KEY (relatedUserId) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_3` FOREIGN KEY (relatedPublicationId) REFERENCES publication (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_4` FOREIGN KEY (relatedCommentaireId) REFERENCES commentaire (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('CREATE INDEX idx_notif_seen ON notification (seen)');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476ca99a3424d TO relatedUserId');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476ca4ad5f91 TO relatedPublicationId');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476ca229fa9c7 TO relatedCommentaireId');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476ca64b64dcc TO idx_notif_user');
        $this->addSql('ALTER TABLE participation_evenement ADD idEmploye INT UNSIGNED NOT NULL, ADD creeLe DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, DROP id_employe, DROP cree_le, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE idEvenement idEvenement INT UNSIGNED NOT NULL, CHANGE date_participation dateParticipation DATE NOT NULL');
        $this->addSql('ALTER TABLE participation_evenement RENAME INDEX idx_65a14675f7cc4348 TO fk_participation_evenement');
        $this->addSql('ALTER TABLE pdi DROP FOREIGN KEY FK_9E4FC61D1B65292');
        $this->addSql('ALTER TABLE pdi ADD progressionGlobale INT DEFAULT NULL, ADD dateCreation DATE DEFAULT NULL, DROP progression_globale, DROP date_creation, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE pdi ADD CONSTRAINT `fk_pdi_employe` FOREIGN KEY (employe_id) REFERENCES employe_competence (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pdi ADD CONSTRAINT `fk_pdi_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pdi RENAME INDEX idx_9e4fc61d1b65292 TO fk_pdi_utilisateur');
        $this->addSql('ALTER TABLE pipeline_etape CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE poste_externe_id poste_externe_id INT DEFAULT NULL, CHANGE ordre ordre INT DEFAULT NULL, CHANGE libelle libelle VARCHAR(100) DEFAULT NULL, CHANGE description_etape description_etape TEXT DEFAULT NULL, CHANGE duree_moyenne duree_moyenne INT DEFAULT NULL, CHANGE action_automatique action_automatique VARCHAR(100) DEFAULT NULL, CHANGE obligatoire obligatoire TINYINT DEFAULT NULL');
        $this->addSql('CREATE INDEX fk_pipeline_poste ON pipeline_etape (poste_externe_id)');
        $this->addSql('ALTER TABLE poll ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, ADD closedAt DATETIME DEFAULT NULL, ADD totalVotes INT DEFAULT 0, ADD expiresAt DATETIME DEFAULT NULL, ADD isAnonymous TINYINT DEFAULT 0, ADD allowMultiple TINYINT DEFAULT 0, ADD createdById INT DEFAULT 1 NOT NULL, DROP created_at, DROP closed_at, DROP total_votes, DROP expires_at, DROP is_anonymous, DROP allow_multiple, DROP created_by_id, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE poll RENAME INDEX idx_84bcfa45796da8a TO publicationId');
        $this->addSql('ALTER TABLE poll_option ADD pollId INT NOT NULL, ADD voteCount INT DEFAULT 0, ADD optionOrder INT DEFAULT 0, DROP poll_id, DROP vote_count, DROP option_order, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE option_text optionText VARCHAR(200) NOT NULL');
        $this->addSql('CREATE INDEX pollId ON poll_option (pollId)');
        $this->addSql('ALTER TABLE poll_vote ADD pollId INT NOT NULL, ADD optionId INT NOT NULL, ADD userId INT NOT NULL, ADD votedAt DATETIME DEFAULT CURRENT_TIMESTAMP, DROP poll_id, DROP option_id, DROP user_id, DROP voted_at, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_vote ON poll_vote (pollId, optionId, userId)');
        $this->addSql('CREATE INDEX optionId ON poll_vote (optionId)');
        $this->addSql('ALTER TABLE poste_externe CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE type_contrat type_contrat VARCHAR(50) DEFAULT NULL, CHANGE salaire salaire DOUBLE PRECISION DEFAULT NULL, CHANGE competences_requises competences_requises TEXT DEFAULT NULL, CHANGE experience_requise experience_requise INT DEFAULT NULL, CHANGE niveau_etude_requis niveau_etude_requis VARCHAR(50) DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE date_publication date_publication DATE DEFAULT NULL, CHANGE date_cloture date_cloture DATE DEFAULT NULL, CHANGE nombre_employe nombre_employe INT DEFAULT NULL, CHANGE priorite priorite INT DEFAULT NULL');
        $this->addSql('ALTER TABLE poste_interne CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE publication CHANGE contenu contenu TEXT NOT NULL, CHANGE dateCreation dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE statut statut ENUM(\'ACTIF\', \'SUPPRIME\', \'ARCHIVE\') DEFAULT \'ACTIF\', CHANGE nombreCommentaires nombreCommentaires INT DEFAULT 0, CHANGE nombreReactions nombreReactions INT DEFAULT 0, CHANGE visibility visibility VARCHAR(20) DEFAULT \'PUBLIC\', CHANGE authorId authorId INT NOT NULL');
        $this->addSql('CREATE INDEX idx_pub_date ON publication (dateCreation)');
        $this->addSql('CREATE INDEX idx_pub_statut ON publication (statut)');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_af3c6779a196f9fd TO idx_pub_author');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_af3c6779d7a914d7 TO idx_pub_shared');
        $this->addSql('ALTER TABLE publication RENAME INDEX idx_af3c6779ed8188b0 TO idx_publication_group');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_6033B00BAFC2B591');
        $this->addSql('ALTER TABLE quiz_question CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE question question TEXT NOT NULL, CHANGE option_c option_c VARCHAR(255) DEFAULT NULL, CHANGE option_d option_d VARCHAR(255) DEFAULT NULL, CHANGE bonne_reponse bonne_reponse CHAR(1) NOT NULL, CHANGE explication explication TEXT DEFAULT NULL, CHANGE module_id module_id INT NOT NULL');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT `quiz_question_ibfk_1` FOREIGN KEY (module_id) REFERENCES module (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question RENAME INDEX idx_6033b00bafc2b591 TO idx_quiz_module');
        $this->addSql('ALTER TABLE reaction CHANGE type type ENUM(\'LIKE\', \'LOVE\', \'LAUGH\', \'WOW\', \'SAD\', \'ANGRY\') DEFAULT \'LIKE\', CHANGE dateCreation dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE userId userId INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_reaction_pub ON reaction (userId, publicationId)');
        $this->addSql('CREATE UNIQUE INDEX unique_reaction_comment ON reaction (userId, commentaireId)');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_a4d707f764b64dcc TO idx_reaction_user');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_a4d707f7796da8a TO idx_reaction_pub');
        $this->addSql('ALTER TABLE reaction RENAME INDEX idx_a4d707f721a42cdc TO idx_reaction_comment');
        $this->addSql('ALTER TABLE reservation CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE chair_id chair_id INT DEFAULT NULL, CHANGE reservation_date reservation_date DATE DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL');
        $this->addSql('CREATE INDEX chair_id ON reservation (chair_id)');
        $this->addSql('ALTER TABLE reservation_espaces ADD idEmploye INT UNSIGNED NOT NULL, ADD dateHeureDebut DATETIME NOT NULL, ADD dateHeureFin DATETIME NOT NULL, ADD creeLe DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, DROP id_employe, DROP date_heure_debut, DROP date_heure_fin, DROP cree_le, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE objectif objectif VARCHAR(255) DEFAULT NULL, CHANGE statut statut TINYINT DEFAULT 1, CHANGE idEspace idEspace INT UNSIGNED NOT NULL, CHANGE date_reservation dateReservation DATE NOT NULL');
        $this->addSql('ALTER TABLE reservation_espaces RENAME INDEX idx_4f9ec26265baa1f7 TO fk_reservation_space');
        $this->addSql('ALTER TABLE resultatevaluation DROP FOREIGN KEY FK_3E592CCB456C5646');
        $this->addSql('ALTER TABLE resultatevaluation DROP FOREIGN KEY FK_3E592CCB1B65292');
        $this->addSql('ALTER TABLE resultatevaluation ADD datePassage DATE DEFAULT NULL, DROP date_passage, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE note note DOUBLE PRECISION DEFAULT NULL, CHANGE statut statut VARCHAR(100) DEFAULT NULL, CHANGE commentaire commentaire VARCHAR(255) DEFAULT NULL, CHANGE score_pct score_pct INT DEFAULT NULL, CHANGE niveau_delta niveau_delta INT DEFAULT 0, CHANGE evaluation_id evaluation_id INT NOT NULL');
        $this->addSql('ALTER TABLE resultatevaluation ADD CONSTRAINT `fk_resultat_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultatevaluation ADD CONSTRAINT `fk_resultatEvaluation_employe` FOREIGN KEY (employe_id) REFERENCES employe_competence (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultatevaluation ADD CONSTRAINT `resultatevaluation_ibfk_1` FOREIGN KEY (evaluation_id) REFERENCES evaluationformation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultatevaluation RENAME INDEX idx_3e592ccb456c5646 TO idx_resultat_evaluation');
        $this->addSql('ALTER TABLE resultatevaluation RENAME INDEX idx_3e592ccb1b65292 TO fk_resultat_utilisateur');
        $this->addSql('ALTER TABLE reunion ADD dateHeureDebut DATETIME NOT NULL, ADD dateHeureFin DATETIME NOT NULL, ADD nomOrganisateur VARCHAR(255) NOT NULL, ADD emailOrganisateur VARCHAR(255) NOT NULL, ADD enLigne TINYINT DEFAULT 0 NOT NULL, ADD creeLe DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, DROP date_heure_debut, DROP date_heure_fin, DROP nom_organisateur, DROP email_organisateur, DROP en_ligne, DROP cree_le, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE participants participants LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE statut statut TINYINT DEFAULT 1, CHANGE zoom_meeting_id zoom_meeting_id BIGINT DEFAULT 0, CHANGE zoom_join_url zoom_join_url VARCHAR(512) DEFAULT NULL, CHANGE zoom_start_url zoom_start_url VARCHAR(512) DEFAULT NULL, CHANGE zoom_password zoom_password VARCHAR(64) DEFAULT NULL, CHANGE idSalle idSalle INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE reunion RENAME INDEX idx_5b00a48259533d41 TO fk_reunion_room');
        $this->addSql('ALTER TABLE savedpost CHANGE savedAt savedAt DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE userId userId INT NOT NULL, CHANGE publicationId publicationId INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_saved ON savedpost (userId, publicationId)');
        $this->addSql('ALTER TABLE savedpost RENAME INDEX idx_f39b527f64b64dcc TO idx_saved_user');
        $this->addSql('ALTER TABLE savedpost RENAME INDEX idx_f39b527f796da8a TO idx_saved_pub');
        $this->addSql('ALTER TABLE sessionformation DROP FOREIGN KEY FK_E52C04B75200282E');
        $this->addSql('ALTER TABLE sessionformation ADD dateDebut DATE NOT NULL, ADD dateFin DATE NOT NULL, DROP date_debut, DROP date_fin, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE lieu lieu VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(100) DEFAULT NULL, CHANGE formation_id formation_id INT NOT NULL');
        $this->addSql('ALTER TABLE sessionformation ADD CONSTRAINT `sessionformation_ibfk_1` FOREIGN KEY (formation_id) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sessionformation RENAME INDEX idx_e52c04b75200282e TO idx_session_formation');
        $this->addSql('ALTER TABLE share DROP FOREIGN KEY FK_EF069D5A64B64DCC');
        $this->addSql('ALTER TABLE share DROP FOREIGN KEY FK_EF069D5A796DA8A');
        $this->addSql('ALTER TABLE share CHANGE shareCount shareCount INT DEFAULT 0 NOT NULL, CHANGE userId userId INT NOT NULL, CHANGE publicationId publicationId INT NOT NULL');
        $this->addSql('CREATE INDEX idx_share_sharedAt ON share (sharedAt)');
        $this->addSql('ALTER TABLE share RENAME INDEX idx_ef069d5a64b64dcc TO idx_share_userId');
        $this->addSql('ALTER TABLE share RENAME INDEX idx_ef069d5a796da8a TO idx_share_publicationId');
        $this->addSql('ALTER TABLE sous_section_progression DROP FOREIGN KEY FK_6E07BF081B65292');
        $this->addSql('ALTER TABLE sous_section_progression DROP FOREIGN KEY FK_6E07BF083E5BB690');
        $this->addSql('ALTER TABLE sous_section_progression CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut ENUM(\'not_started\', \'completed\') DEFAULT \'not_started\', CHANGE date_completion date_completion DATETIME DEFAULT NULL, CHANGE employe_id employe_id INT NOT NULL, CHANGE sous_section_id sous_section_id INT NOT NULL');
        $this->addSql('ALTER TABLE sous_section_progression ADD CONSTRAINT `fk_ssprog_utilisateur` FOREIGN KEY (employe_id) REFERENCES utilisateur (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sous_section_progression ADD CONSTRAINT `sous_section_progression_ibfk_1` FOREIGN KEY (employe_id) REFERENCES employe_competence (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sous_section_progression ADD CONSTRAINT `sous_section_progression_ibfk_2` FOREIGN KEY (sous_section_id) REFERENCES module_sous_section (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_emp_ss ON sous_section_progression (employe_id, sous_section_id)');
        $this->addSql('ALTER TABLE sous_section_progression RENAME INDEX idx_6e07bf083e5bb690 TO sous_section_id');
        $this->addSql('ALTER TABLE sous_section_progression RENAME INDEX idx_6e07bf081b65292 TO idx_ssprog_emp');
        $this->addSql('ALTER TABLE type_absence CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE type_conge CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE userprofile DROP INDEX IDX_1D3656B164B64DCC, ADD UNIQUE INDEX userId (userId)');
        $this->addSql('ALTER TABLE userprofile ADD avatarUrl VARCHAR(500) DEFAULT NULL, ADD coverUrl VARCHAR(500) DEFAULT NULL, ADD jobTitle VARCHAR(100) DEFAULT NULL, ADD followersCount INT DEFAULT 0, ADD followingCount INT DEFAULT 0, ADD postsCount INT DEFAULT 0, DROP avatar_url, DROP cover_url, DROP job_title, DROP followers_count, DROP following_count, DROP posts_count, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE bio bio TEXT DEFAULT NULL, CHANGE location location VARCHAR(100) DEFAULT NULL, CHANGE website website VARCHAR(200) DEFAULT NULL, CHANGE company company VARCHAR(100) DEFAULT NULL, CHANGE userId userId INT NOT NULL');
        $this->addSql('ALTER TABLE users CHANGE bio bio TEXT DEFAULT NULL, CHANGE createdAt createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updatedAt updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE isActive isActive TINYINT DEFAULT 1, CHANGE role role VARCHAR(20) DEFAULT \'EMPLOYEE\', CHANGE isOnline isOnline TINYINT DEFAULT 0');
        $this->addSql('CREATE UNIQUE INDEX username ON users (username)');
        $this->addSql('CREATE UNIQUE INDEX email ON users (email)');
        $this->addSql('CREATE INDEX idx_users_username ON users (username)');
        $this->addSql('CREATE INDEX idx_users_email ON users (email)');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role ENUM(\'ADMIN\', \'EMPLOYE\', \'MANAGER\', \'RH\', \'FORMATEUR\') DEFAULT NULL, CHANGE statut statut ENUM(\'Archive\', \'Actif\', \'Inactif\', \'bloque\', \'suspendu\') DEFAULT \'Actif\' NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE donnees_faciales donnees_faciales BLOB DEFAULT NULL, CHANGE mfa_enabled mfa_enabled TINYINT DEFAULT 0, CHANGE is_online is_online TINYINT DEFAULT 0, CHANGE poste_actuel posteActuel VARCHAR(150) DEFAULT NULL, CHANGE date_embauche dateEmbauche DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX uniq_1d1c63b3e7927c74 TO email');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX uniq_1d1c63b3f85e0677 TO username');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX idx_1d1c63b3783e3463 TO fk_manager');
    }
}
